version: "3.8"

services:
  plescapi:
    volumes:
      - /Users/matt/Desktop/plesc-455015-5e588ea78c9c.json:/app/plesc-455015-5e588ea78c9c.json
    develop:
      watch:
        - action: rebuild
          path: ./app
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env