apiVersion: v1
kind: Service
metadata:
  name: plescapi-service
  labels:
    app: plescapi
spec:
  selector:
    app: plescapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer 