name: 'Build and Deploy to GKE'

on:
  workflow_call:
    secrets:
      GKE_SA_KEY:
        required: true
        description: 'Google Cloud Service Account Key'

env:
  PROJECT_ID: 'plesc-455015'
  GAR_LOCATION: 'us-central1'
  GKE_CLUSTER: 'eva-01'
  GKE_ZONE: 'us-central1-c'
  DEPLOYMENT_NAME: 'plescapi'
  REPOSITORY: 'plesc-docker'
  IMAGE: 'plescapi'

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Google Cloud Auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}' 

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - name: Docker configuration
        run: |-
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

      # Get the GKE credentials so we can deploy to the cluster
      - name: 'Set up GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_ZONE }}'

      # Build the Docker image
      - name: 'Build and push Docker container'
        run: |-
          DOCKER_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA}"
          DOCKER_LATEST_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:latest"

          docker build \
            --tag "${DOCKER_TAG}" \
            --tag "${DOCKER_LATEST_TAG}" \
            --build-arg GITHUB_SHA="${GITHUB_SHA}" \
            --build-arg GITHUB_REF="${GITHUB_REF}" \
            .

          docker push "${DOCKER_TAG}"
          docker push "${DOCKER_LATEST_TAG}"

      # Deploy the Docker image to the GKE cluster
      - name: 'Deploy to GKE'
        run: |-
          sed -i "s/\${GITHUB_SHA}/${GITHUB_SHA}/g" deployment.yml
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          kubectl get pods
